name: PROD Build and deploy app-we-azn-prd-01
on:
  push:
    branches:
    - main
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: app-we-azn-prd-01
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'
        include-prerelease: true
        
    - name: Build with dotnet
      run: dotnet build "./src" --configuration Release
      
    - name: dotnet publish
      run: dotnet publish "./src" -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.AZURE_WEBAPP_NAME }}
        path: ${{env.DOTNET_ROOT}}/myapp
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.AZURE_WEBAPP_NAME }}
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
